version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./src/services/backend
    ports:
      - 5000:80
  frontend:
    container_name: frontend
    depends_on: [backend]
    build:
      context: ./src/services/frontend
      args:
        GENERATE_SOURCEMAP: "false"
    ports:
      - 7000:80
