version: "3.7"

services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./src/services/frontend/Dockerfile
    ports:
      - 7000:80
    environment:
      NODE_ENV: production
